name: summon-platform-CI
on:
  push:
  workflow_dispatch:
jobs:
    Build-docker-image:
        name: docker_image
        runs-on: ubuntu-latest
        steps:
            - name: check for deploy
              if: ${{ contains(github.event.head_commit.message, 'deploy') }}
              run: |
                # DEPLOY=$(echo "${{github.event.head_commit.message}}"  | sed -En 's/.*\[deploy\:(.*|\ .*)\]/\1/p' | awk '{$1=$1;print}')
                # echo "DEPLOY=$DEPLOY"
                DEPLOY=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*\[deploy:[[:space:]]*\([^]]*\)].*/\1/p')
                echo "DEPLOY=$DEPLOY"

            - name: checkout code
              uses: actions/checkout@v4
              
            - name: directory  
              run: |
               echo "Current directory: $(pwd)"
               ls -ltra
                

            # - name: create PR to deploy latest build to tanent
            #   if : env.DEPLOY != null
            #   uses: actions/checkout@v4
            #   with:
            #     repository: ajinkyak423/actions-poc

      