name: summon-platform-CI

on:
  push:
  workflow_dispatch:

jobs:
  Build-docker-image:
    name: docker_image
    runs-on: ubuntu-latest
    steps:
      - name: check for deploy
        if: contains(github.event.head_commit.message, 'deploy')
        run: |
          DEPLOY=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*\[deploy:[[:space:]]*\([^]]*\)].*/\1/p')
          echo "DEPLOY=$DEPLOY"

      - name: checkout code
        uses: actions/checkout@v3  # Version 4 is not valid, using version 2

      - name: change directory
        run: |
          echo "Current directory: $(pwd)"
          cd ../..  # Adjust this based on your project structure
          echo "Current directory: $(pwd)"

      - name: create PR to deploy latest build to tenant
        uses: actions/checkout@v3  # Using version 2
        with:
          repository: ajinkyak423/actions-poc
        # Add steps for creating a pull request here

      - name: directory  
        run: |
          echo "Current directory: $(pwd)"
          ls -ltra
