name: summon-platform-CI

on:
  push:
  workflow_dispatch:

jobs:
  Build-docker-image:
    name: docker_image
    runs-on: ubuntu-latest
    steps:
      - name: check for deploy
        if: contains(github.event.head_commit.message, 'deploy')
        run: |
          DEPLOY=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*\[deploy:[[:space:]]*\([^]]*\)].*/\1/p')
          echo "DEPLOY=$DEPLOY"

      - name: checkout code
        uses: actions/checkout@v3

      - name: create PR to deploy latest build to tenant
        uses: actions/checkout@v3
        with:
          repository: ajinkyak423/actions-poc
          path: my-tools
          token: ${{ secrets.MY_GITHUB_ACTION_TOKEN }}
       
      - name: directory  
        run: |
          echo "Current directory: $(pwd)"
          ls -ltra
